# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require 'digest'
require 'fileutils'

CHAT_BOTTOM_CONTAINER_FRAMEWORK_URL = 'https://github.com/LinXunFeng/flutter_chat_packages_pub/releases/download/chat_bottom_container/ios_0.0.1.zip'
CHAT_BOTTOM_CONTAINER_FRAMEWORK_SHA256 = 'b9c380b72010e5d378cc813fbc5cca9b21471b82134e633567a6beee4b5a2a91'

def prepare_chat_bottom_container_binary
  plugin_ios_dir = File.expand_path('.symlinks/plugins/chat_bottom_container/ios', __dir__)
  podspec_path = File.join(plugin_ios_dir, 'chat_bottom_container.podspec')
  return unless File.exist?(podspec_path)

  framework_dir = File.join(plugin_ios_dir, 'chat_bottom_container', 'Frameworks')
  framework_path = File.join(framework_dir, 'FSAChatBottomContainer.xcframework')
  unless File.directory?(framework_path)
    FileUtils.rm_rf(framework_dir)
    FileUtils.mkdir_p(framework_dir)

    zip_path = File.join(framework_dir, 'ios_0.0.1.zip')
    system('curl', '-L', '-f', '-o', zip_path, CHAT_BOTTOM_CONTAINER_FRAMEWORK_URL) ||
      raise('下载 FSAChatBottomContainer.xcframework 失败')

    actual_sha256 = Digest::SHA256.file(zip_path).hexdigest
    unless actual_sha256 == CHAT_BOTTOM_CONTAINER_FRAMEWORK_SHA256
      raise("FSAChatBottomContainer.xcframework 校验失败：#{actual_sha256}")
    end

    system('unzip', '-q', zip_path, '-d', framework_dir) ||
      raise('解压 FSAChatBottomContainer.xcframework 失败')
    File.delete(zip_path)
  end

  podspec = File.read(podspec_path)
  return if podspec.include?('FSAChatBottomContainer.xcframework')

  vendored_framework = "  s.vendored_frameworks = 'chat_bottom_container/Frameworks/FSAChatBottomContainer.xcframework'\n"
  unless podspec.sub!("  s.dependency 'Flutter'\n", "  s.dependency 'Flutter'\n#{vendored_framework}")
    raise('更新 chat_bottom_container.podspec 失败')
  end
  File.write(podspec_path, podspec)
end

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  prepare_chat_bottom_container_binary
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # Start of the permission_handler configuration
        target.build_configurations.each do |config|

          # You can enable the permissions needed here. For example to enable camera
          # permission, just remove the `#` character in front so it looks like this:
          #
          # ## dart: PermissionGroup.camera
          # 'PERMISSION_CAMERA=1'
          #
          #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler_apple/ios/Classes/PermissionHandlerEnums.h
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',

            ## dart: PermissionGroup.calendar
            # 'PERMISSION_EVENTS=1',

            ## dart: PermissionGroup.reminders
            # 'PERMISSION_REMINDERS=1',

            ## dart: PermissionGroup.contacts
            # 'PERMISSION_CONTACTS=1',

            ## dart: PermissionGroup.camera
            # 'PERMISSION_CAMERA=1',

            ## dart: PermissionGroup.microphone
            # 'PERMISSION_MICROPHONE=1',

            ## dart: PermissionGroup.speech
            # 'PERMISSION_SPEECH_RECOGNIZER=1',

            ## dart: PermissionGroup.photos
            'PERMISSION_PHOTOS=1',

            ## dart: PermissionGroup.photosAddOnly
            # 'PERMISSION_PHOTOS_ADD_ONLY =1',

            ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
            # 'PERMISSION_LOCATION=1',

            ## dart: PermissionGroup.notification
            # 'PERMISSION_NOTIFICATIONS=1',

            ## dart: PermissionGroup.mediaLibrary
            # 'PERMISSION_MEDIA_LIBRARY=1',

            ## dart: PermissionGroup.sensors
            # 'PERMISSION_SENSORS=1',

            ## dart: PermissionGroup.bluetooth
            # 'PERMISSION_BLUETOOTH=1',

            ## dart: PermissionGroup.appTrackingTransparency
            # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

            ## dart: PermissionGroup.criticalAlerts
            # 'PERMISSION_CRITICAL_ALERTS=1'
          ]

        end
        # End of the permission_handler configuration
  end
end
